version: '3.7'
services:
  ignite-streaming-app:
    image: ignite-streaming-app
    container_name: ignite-streaming-app
    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '0.33'
    environment:
      - CONFIG_URI=/opt/ignite/ext-config/ignite-config-node.xml
      - LICENCE_URL=/opt/ignite/ext-config/gridgain-ultimate-license.xml
      - IGNITE_EVENT_DRIVEN_SERVICE_PROCESSOR_ENABLED=true
      - IGNITE_WORK_DIR=/opt/ignite/work
      - execTime=150
    networks:
      - ignite-net
    volumes:
      - ../config:/opt/ignite/ext-config
      - ../work:/opt/ignite/work

networks:
  ignite-net:
    driver: bridge

volumes:
  config:
    external: true